module.exports = {
  'bonoloto': 'bonoloto',
  'el-gordo-primitiva': 'el-gordo',
  'eurojackpot': 'eurojackpot',
  'euromillions': 'euromillions',
  'euromillions-ie': 'euromillions',
  'la-primitiva': 'la-primitiva',
  'lotto-fr': 'french-lottery',
  'lotto-ie': 'irish-lottery',
  'lotto-pl': 'polish-lottery',
  'lotto-uk': 'national-lottery',
  'megamillions': 'mega-millions',
  'megasena': 'mega-sena',
  'oz-lotto-au': 'oz-lotto',
  'powerball': 'powerball',
  'powerball-au': 'oz-powerball',
  'superenalotto': 'superenalotto',
  'thunderball': 'thunderball',
  'lotto-6aus49': 'lotto-6aus49',
};
